<?php

declare(strict_types=1);

namespace App\Service;

use App\Entity\NonConformity;
use App\Repository\NonConformityRepository;

/**
 * Assigns the autogenerated reference of a {@see NonConformity}.
 *
 * Format: {@code NC.<originCode>.<year>.<NN>} (e.g. "NC.AE.2026.01"). The shape keeps the
 * centre's existing nomenclature (NC.AE.NN) and adds the year the procedure PC.10.0 mandates,
 * with the sequence reset per (origin, year). This is the single place to change the format if
 * the centre prefers the legacy year-less code.
 */
final class NonConformityReferenceGenerator
{
    public function __construct(private readonly NonConformityRepository $repository)
    {
    }

    /**
     * Fills the year, sequence and reference of a not-yet-persisted non-conformity from its
     * origin and opening date. Idempotent guard: only assigns when no reference is set yet.
     *
     * @param NonConformity $nonConformity the non-conformity to stamp (mutated in place)
     */
    public function assign(NonConformity $nonConformity): void
    {
        $year = (int) $nonConformity->getOpenedAt()->format('Y');
        $sequence = $this->repository->nextSequence($nonConformity->getOrigin(), $year);

        $nonConformity
            ->setYear($year)
            ->setSequence($sequence)
            ->setReference($this->format($nonConformity->getOrigin()->code(), $year, $sequence));
    }

    /**
     * Builds the reference string from its parts.
     *
     * @param string $originCode the origin short code (e.g. "AE")
     * @param int    $year       the reference year
     * @param int    $sequence   the per-(origin, year) sequence
     *
     * @return string the formatted reference (e.g. "NC.AE.2026.01")
     */
    private function format(string $originCode, int $year, int $sequence): string
    {
        return sprintf('NC.%s.%d.%02d', $originCode, $year, $sequence);
    }
}
