<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\ComplianceStatus;
use App\Enum\EvaluationFrequency;
use App\Enum\LegalScope;
use App\Repository\LegalRequirementRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A legal (or other) requirement applicable to the centre and the evaluation of its compliance
 * (PC-06.03 / register "Lista de requisitos legales"). A non-compliant requirement is a candidate
 * for opening a non-conformity.
 */
#[ORM\Entity(repositoryClass: LegalRequirementRepository::class)]
#[ORM\Table(name: 'legal_requirement')]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['reference'], message: 'Ya existe un requisito legal con esa referencia.')]
class LegalRequirement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Autogenerated human reference, e.g. "RL-01". Assigned once at creation and never recomputed.
     */
    #[ORM\Column(length: 20, unique: true)]
    private string $reference;

    /**
     * Sequential number behind the reference, starting at 1.
     */
    #[ORM\Column]
    private int $sequence;

    /**
     * The legislation or norm ("Disposición legal"), e.g. "Ley 7/2022 de residuos".
     */
    #[ORM\Column(length: 500)]
    #[Assert\NotBlank]
    #[Assert\Length(max: 500)]
    private string $legalProvision;

    #[ORM\Column(length: 20, enumType: LegalScope::class)]
    private LegalScope $scope;

    /**
     * Environmental vector affected ("Vector ambiental afectado"), e.g. residuos, vertidos,
     * emisiones. Free text since legislation touches varied vectors.
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max: 255)]
    private ?string $environmentalVector = null;

    /**
     * The concrete task/control the centre must fulfil ("Requisito específico").
     */
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private string $specificRequirement;

    /**
     * Evidence supporting compliance ("Evidencia de cumplimiento"); null while none recorded.
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $complianceEvidence = null;

    #[ORM\Column(length: 20, enumType: ComplianceStatus::class)]
    private ComplianceStatus $complianceStatus = ComplianceStatus::PENDING;

    #[ORM\Column(length: 20, nullable: true, enumType: EvaluationFrequency::class)]
    private ?EvaluationFrequency $evaluationFrequency = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $lastReviewedOn = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $nextReviewOn = null;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column]
    private \DateTimeImmutable $updatedAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = $this->createdAt;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * Whether this requirement is currently evaluated as non-compliant.
     */
    public function isNonCompliant(): bool
    {
        return ComplianceStatus::NON_COMPLIANT === $this->complianceStatus;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getSequence(): int
    {
        return $this->sequence;
    }

    public function setSequence(int $sequence): static
    {
        $this->sequence = $sequence;

        return $this;
    }

    public function getLegalProvision(): string
    {
        return $this->legalProvision;
    }

    public function setLegalProvision(string $legalProvision): static
    {
        $this->legalProvision = $legalProvision;

        return $this;
    }

    public function getScope(): LegalScope
    {
        return $this->scope;
    }

    public function setScope(LegalScope $scope): static
    {
        $this->scope = $scope;

        return $this;
    }

    public function getEnvironmentalVector(): ?string
    {
        return $this->environmentalVector;
    }

    public function setEnvironmentalVector(?string $environmentalVector): static
    {
        $this->environmentalVector = $environmentalVector;

        return $this;
    }

    public function getSpecificRequirement(): string
    {
        return $this->specificRequirement;
    }

    public function setSpecificRequirement(string $specificRequirement): static
    {
        $this->specificRequirement = $specificRequirement;

        return $this;
    }

    public function getComplianceEvidence(): ?string
    {
        return $this->complianceEvidence;
    }

    public function setComplianceEvidence(?string $complianceEvidence): static
    {
        $this->complianceEvidence = $complianceEvidence;

        return $this;
    }

    public function getComplianceStatus(): ComplianceStatus
    {
        return $this->complianceStatus;
    }

    public function setComplianceStatus(ComplianceStatus $complianceStatus): static
    {
        $this->complianceStatus = $complianceStatus;

        return $this;
    }

    public function getEvaluationFrequency(): ?EvaluationFrequency
    {
        return $this->evaluationFrequency;
    }

    public function setEvaluationFrequency(?EvaluationFrequency $evaluationFrequency): static
    {
        $this->evaluationFrequency = $evaluationFrequency;

        return $this;
    }

    public function getLastReviewedOn(): ?\DateTimeImmutable
    {
        return $this->lastReviewedOn;
    }

    public function setLastReviewedOn(?\DateTimeImmutable $lastReviewedOn): static
    {
        $this->lastReviewedOn = $lastReviewedOn;

        return $this;
    }

    public function getNextReviewOn(): ?\DateTimeImmutable
    {
        return $this->nextReviewOn;
    }

    public function setNextReviewOn(?\DateTimeImmutable $nextReviewOn): static
    {
        $this->nextReviewOn = $nextReviewOn;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }
}
