<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\Efficacy;
use App\Enum\NonConformityOrigin;
use App\Enum\NonConformityStatus;
use App\Enum\ProcessType;
use App\Repository\NonConformityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * A non-conformity (PC.10.0): any incident where an activity fails to meet a requirement. It is
 * the central node of the SGMA — unmet objectives, legal breaches, supplier incidents, audit
 * findings and exceeded indicator thresholds all converge here as a non-conformity.
 *
 * Each one carries an autogenerated, human-readable {@see $reference}; corrective actions
 * (the PAC) are modelled separately and attached to it.
 */
#[ORM\Entity(repositoryClass: NonConformityRepository::class)]
#[ORM\Table(name: 'non_conformity')]
#[ORM\UniqueConstraint(name: 'uniq_nc_origin_year_sequence', columns: ['origin', 'reference_year', 'sequence'])]
#[ORM\UniqueConstraint(name: 'uniq_nc_auto_source_key', columns: ['auto_source_key'])]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['reference'], message: 'Ya existe una no conformidad con esa referencia.')]
class NonConformity
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Autogenerated human reference, e.g. "NC.AE.2026.01". Assigned once at creation by
     * {@see \App\Service\NonConformityReferenceGenerator} and never recomputed, so it stays a
     * stable identifier even if other fields change.
     */
    #[ORM\Column(length: 30, unique: true)]
    private string $reference;

    #[ORM\Column(length: 30, enumType: NonConformityOrigin::class)]
    private NonConformityOrigin $origin;

    /**
     * Free-text detail of the origin, e.g. the audit phase ("Fase I") or the internal trigger.
     */
    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(max: 255)]
    private ?string $originDetail = null;

    /**
     * The specific audit (PC.09.0) this non-conformity was raised in, when it comes from one. Only
     * meaningful for the audit origins; null otherwise. The finding itself lives here (not in the
     * audit), so an audit's non-conformities stay traceable without being entered twice. The FK is
     * SET NULL on delete: removing an audit must not cascade-delete its non-conformities.
     */
    #[ORM\ManyToOne(targetEntity: SystemAudit::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?SystemAudit $audit = null;

    /**
     * Idempotency key of the source that auto-opened this non-conformity, e.g.
     * "indicator_measurement:123" or "objective:45". Null for non-conformities entered by hand. It
     * is unique (see the named constraint on the class) so the auto-generation engine never opens
     * the same one twice (PC.10.0), and it lets a finding be traced back to what triggered it.
     */
    #[ORM\Column(length: 191, nullable: true)]
    private ?string $autoSourceKey = null;

    /**
     * Year the reference belongs to (the sequence resets each year). Set together with
     * {@see $sequence} by the reference generator.
     */
    #[ORM\Column(name: 'reference_year')]
    private int $year;

    /**
     * Sequential number within the (origin, year), starting at 1.
     */
    #[ORM\Column]
    private int $sequence;

    /**
     * ISO 14001:2015 clause breached ("Apartado de la Norma"), e.g. "6.1.2".
     */
    #[ORM\Column(length: 30, nullable: true)]
    #[Assert\Length(max: 30)]
    private ?string $isoClause = null;

    #[ORM\Column(length: 20, nullable: true, enumType: ProcessType::class)]
    private ?ProcessType $affectedProcess = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private string $description;

    /**
     * Root-cause analysis ("Análisis de causas"), filled during evaluation; null while pending.
     */
    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $rootCause = null;

    /**
     * Person accountable for the non-conformity ("Responsable de la NC"). Nullable so a module
     * can open one before the responsible is assigned.
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $responsible = null;

    #[ORM\Column(length: 20, enumType: NonConformityStatus::class)]
    private NonConformityStatus $status = NonConformityStatus::OPEN;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull]
    private \DateTimeImmutable $openedAt;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $closedAt = null;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column]
    private \DateTimeImmutable $updatedAt;

    /**
     * The action plan (PAC): corrective actions adopted in response to this non-conformity.
     *
     * @var Collection<int, CorrectiveAction>
     */
    #[ORM\OneToMany(targetEntity: CorrectiveAction::class, mappedBy: 'nonConformity', cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[ORM\OrderBy(['sequence' => 'ASC'])]
    #[Assert\Valid]
    private Collection $correctiveActions;

    public function __construct()
    {
        $this->openedAt = new \DateTimeImmutable();
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = $this->createdAt;
        $this->correctiveActions = new ArrayCollection();
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getOrigin(): NonConformityOrigin
    {
        return $this->origin;
    }

    public function setOrigin(NonConformityOrigin $origin): static
    {
        $this->origin = $origin;

        return $this;
    }

    public function getOriginDetail(): ?string
    {
        return $this->originDetail;
    }

    public function setOriginDetail(?string $originDetail): static
    {
        $this->originDetail = $originDetail;

        return $this;
    }

    /**
     * The audit this non-conformity was raised in, or null if it does not come from one.
     *
     * @return SystemAudit|null the originating audit, or null
     */
    public function getAudit(): ?SystemAudit
    {
        return $this->audit;
    }

    /**
     * Links the non-conformity to the audit it was raised in.
     *
     * @param SystemAudit|null $audit the originating audit, or null to unlink it
     */
    public function setAudit(?SystemAudit $audit): static
    {
        $this->audit = $audit;

        return $this;
    }

    /**
     * The idempotency key of the source that auto-opened this non-conformity, or null if it was
     * entered by hand.
     *
     * @return string|null the source key, or null
     */
    public function getAutoSourceKey(): ?string
    {
        return $this->autoSourceKey;
    }

    /**
     * Marks the source that auto-opened this non-conformity.
     *
     * @param string|null $autoSourceKey the source key (e.g. "indicator_measurement:123"), or null
     */
    public function setAutoSourceKey(?string $autoSourceKey): static
    {
        $this->autoSourceKey = $autoSourceKey;

        return $this;
    }

    public function getYear(): int
    {
        return $this->year;
    }

    public function setYear(int $year): static
    {
        $this->year = $year;

        return $this;
    }

    public function getSequence(): int
    {
        return $this->sequence;
    }

    public function setSequence(int $sequence): static
    {
        $this->sequence = $sequence;

        return $this;
    }

    public function getIsoClause(): ?string
    {
        return $this->isoClause;
    }

    public function setIsoClause(?string $isoClause): static
    {
        $this->isoClause = $isoClause;

        return $this;
    }

    public function getAffectedProcess(): ?ProcessType
    {
        return $this->affectedProcess;
    }

    public function setAffectedProcess(?ProcessType $affectedProcess): static
    {
        $this->affectedProcess = $affectedProcess;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getRootCause(): ?string
    {
        return $this->rootCause;
    }

    public function setRootCause(?string $rootCause): static
    {
        $this->rootCause = $rootCause;

        return $this;
    }

    public function getResponsible(): ?User
    {
        return $this->responsible;
    }

    public function setResponsible(?User $responsible): static
    {
        $this->responsible = $responsible;

        return $this;
    }

    public function getStatus(): NonConformityStatus
    {
        return $this->status;
    }

    public function setStatus(NonConformityStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Soft closure rule (PC.10.0 §4.3.4): a non-conformity may only be closed once every corrective
     * action has been reviewed effective (efficacy OK). A pending review (efficacy null) blocks
     * closure, and a NO-OK review means the procedure must be reopened, not closed. A
     * non-conformity resolved by an immediate correction (no corrective actions) can still be
     * closed — that leniency keeps minor cases unencumbered.
     */
    #[Assert\Callback]
    public function validateClosure(ExecutionContextInterface $context): void
    {
        if (NonConformityStatus::CLOSED !== $this->status) {
            return;
        }

        foreach ($this->correctiveActions as $action) {
            if (Efficacy::OK !== $action->getEfficacy()) {
                $context->buildViolation('No se puede cerrar la no conformidad mientras alguna acción correctiva no esté verificada como eficaz (OK). Revisa o reabre las acciones pendientes o no eficaces.')
                    ->atPath('status')
                    ->addViolation();

                return;
            }
        }
    }

    public function getOpenedAt(): \DateTimeImmutable
    {
        return $this->openedAt;
    }

    public function setOpenedAt(\DateTimeImmutable $openedAt): static
    {
        $this->openedAt = $openedAt;

        return $this;
    }

    public function getClosedAt(): ?\DateTimeImmutable
    {
        return $this->closedAt;
    }

    public function setClosedAt(?\DateTimeImmutable $closedAt): static
    {
        $this->closedAt = $closedAt;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }

    /**
     * @return Collection<int, CorrectiveAction> the corrective actions of this non-conformity
     */
    public function getCorrectiveActions(): Collection
    {
        return $this->correctiveActions;
    }

    public function addCorrectiveAction(CorrectiveAction $action): static
    {
        if (!$this->correctiveActions->contains($action)) {
            $this->correctiveActions->add($action);
            $action->setNonConformity($this);
        }

        return $this;
    }

    public function removeCorrectiveAction(CorrectiveAction $action): static
    {
        $this->correctiveActions->removeElement($action);

        return $this;
    }
}
