<?php

declare(strict_types=1);

namespace App\Entity;

use App\Enum\ObjectiveStatus;
use App\Repository\ObjectiveRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * An environmental objective of the management system (PG-06.04 / register F.07.01), set yearly by
 * Direction and the RSGMA. Often derives from a significant {@see EnvironmentalAspect}. An unmet
 * objective is a candidate for opening a non-conformity.
 */
#[ORM\Entity(repositoryClass: ObjectiveRepository::class)]
#[ORM\Table(name: 'objective')]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['reference'], message: 'Ya existe un objetivo con esa referencia.')]
class Objective
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    /**
     * Autogenerated human reference, e.g. "OBJ-01". Assigned once at creation, never recomputed.
     */
    #[ORM\Column(length: 20, unique: true)]
    private string $reference;

    #[ORM\Column]
    private int $sequence;

    /**
     * The objective and its target ("Descripción objetivo"), e.g. "Reducir el consumo de agua 5%".
     */
    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank]
    private string $description;

    /**
     * Person accountable for the objective. Nullable so it can be drafted before assignment.
     */
    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: true)]
    private ?User $responsible = null;

    /**
     * Significant environmental aspect that motivates the objective, when applicable.
     */
    #[ORM\ManyToOne(targetEntity: EnvironmentalAspect::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?EnvironmentalAspect $relatedAspect = null;

    /**
     * Target period, free text as the centre records it (e.g. "enero 2025 a marzo 2026").
     */
    #[ORM\Column(length: 120, nullable: true)]
    #[Assert\Length(max: 120)]
    private ?string $targetPeriod = null;

    #[ORM\Column(length: 20, enumType: ObjectiveStatus::class)]
    private ObjectiveStatus $status = ObjectiveStatus::IN_PROGRESS;

    #[ORM\Column(type: Types::DATE_IMMUTABLE, nullable: true)]
    private ?\DateTimeImmutable $lastReviewedOn = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $notes = null;

    #[ORM\Column]
    private \DateTimeImmutable $createdAt;

    #[ORM\Column]
    private \DateTimeImmutable $updatedAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = $this->createdAt;
    }

    #[ORM\PrePersist]
    #[ORM\PreUpdate]
    public function touch(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    /**
     * Whether the objective is currently evaluated as not achieved.
     */
    public function isNotAchieved(): bool
    {
        return ObjectiveStatus::NOT_ACHIEVED === $this->status;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getReference(): string
    {
        return $this->reference;
    }

    public function setReference(string $reference): static
    {
        $this->reference = $reference;

        return $this;
    }

    public function getSequence(): int
    {
        return $this->sequence;
    }

    public function setSequence(int $sequence): static
    {
        $this->sequence = $sequence;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getResponsible(): ?User
    {
        return $this->responsible;
    }

    public function setResponsible(?User $responsible): static
    {
        $this->responsible = $responsible;

        return $this;
    }

    public function getRelatedAspect(): ?EnvironmentalAspect
    {
        return $this->relatedAspect;
    }

    public function setRelatedAspect(?EnvironmentalAspect $relatedAspect): static
    {
        $this->relatedAspect = $relatedAspect;

        return $this;
    }

    public function getTargetPeriod(): ?string
    {
        return $this->targetPeriod;
    }

    public function setTargetPeriod(?string $targetPeriod): static
    {
        $this->targetPeriod = $targetPeriod;

        return $this;
    }

    public function getStatus(): ObjectiveStatus
    {
        return $this->status;
    }

    public function setStatus(ObjectiveStatus $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getLastReviewedOn(): ?\DateTimeImmutable
    {
        return $this->lastReviewedOn;
    }

    public function setLastReviewedOn(?\DateTimeImmutable $lastReviewedOn): static
    {
        $this->lastReviewedOn = $lastReviewedOn;

        return $this;
    }

    public function getNotes(): ?string
    {
        return $this->notes;
    }

    public function setNotes(?string $notes): static
    {
        $this->notes = $notes;

        return $this;
    }

    public function getCreatedAt(): \DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): \DateTimeImmutable
    {
        return $this->updatedAt;
    }
}
