<?php

declare(strict_types=1);

namespace App\Enum;

/**
 * Document taxonomy defined by the documented-information procedure that implements
 * ISO 14001:2015 clause 7.5.
 *
 * A FORM is a blank, versioned template (code F.XX.Y); a RECORD is a filled instance of a
 * form (the actual evidence). EXTERNAL_EVIDENCE covers third-party documents (OCA
 * certificates, invoices, legislation) that are only stored, never generated by the system.
 */
enum DocumentType: string
{
    case POLICY = 'policy';
    case MANUAL = 'manual';
    case PROCEDURE = 'procedure';
    case FORM = 'form';
    case RECORD = 'record';
    case EXTERNAL_EVIDENCE = 'external_evidence';

    /**
     * Whether documents of this type are generated by the system (form-driven PDF)
     * as opposed to being uploaded/archived as opaque attachments.
     *
     * @return bool true if the system generates the document, false if it is only stored
     */
    public function isSystemGenerated(): bool
    {
        return $this !== self::EXTERNAL_EVIDENCE;
    }
}
