<?php

declare(strict_types=1);

namespace App\Enum;

/**
 * Document taxonomy defined by the documented-information procedure that implements
 * ISO 14001:2015 clause 7.5.
 *
 * A FORM is a blank, versioned template (code F.XX.Y); a RECORD is a filled instance of a
 * form (the actual evidence). EXTERNAL_EVIDENCE covers third-party documents (OCA
 * certificates, invoices, legislation) that are only stored, never generated by the system.
 */
enum DocumentType: string
{
    case POLICY = 'policy';
    case MANUAL = 'manual';
    case PROCEDURE = 'procedure';
    case FORM = 'form';
    case RECORD = 'record';
    case EXTERNAL_EVIDENCE = 'external_evidence';

    /**
     * Whether documents of this type are generated by the system (form-driven PDF)
     * as opposed to being uploaded/archived as opaque attachments.
     *
     * @return bool true if the system generates the document, false if it is only stored
     */
    public function isSystemGenerated(): bool
    {
        return $this !== self::EXTERNAL_EVIDENCE;
    }

    /**
     * Human-facing label (Spanish, the application's UI language), following the procedure's
     * five-type taxonomy plus external evidence.
     *
     * @return string the display name
     */
    public function label(): string
    {
        return match ($this) {
            self::POLICY => 'Política',
            self::MANUAL => 'Manual',
            self::PROCEDURE => 'Procedimiento',
            self::FORM => 'Formato',
            self::RECORD => 'Registro',
            self::EXTERNAL_EVIDENCE => 'Evidencia externa',
        };
    }

    /**
     * Code of the role that approves documents of this type (PC.01.0): Dirección approves the
     * policy/manual/procedures, the RSGMA (Responsable del SGA) approves the forms. Records and
     * external evidence are not approved through the revision workflow, so they return null.
     *
     * @return string|null the approving role's code, or null if this type is not approved here
     */
    public function approverRoleCode(): ?string
    {
        return match ($this) {
            self::POLICY, self::MANUAL, self::PROCEDURE => 'direction',
            self::FORM => 'ems_manager',
            self::RECORD, self::EXTERNAL_EVIDENCE => null,
        };
    }
}
