<?php

declare(strict_types=1);

namespace App\Enum;

/**
 * Source (procedencia) of a non-conformity, per procedure PC.10.0: detected during normal
 * internal activity, during an internal audit, or during an external (certification/follow-up)
 * audit.
 *
 * The {@see code()} feeds the autogenerated reference (e.g. "AE" in NC.AE.2026.01), keeping the
 * shape of the centre's existing nomenclature (NC.AE.NN) while the rest of the reference adds the
 * year the procedure mandates.
 */
enum NonConformityOrigin: string
{
    case INTERNAL = 'internal';
    case INTERNAL_AUDIT = 'internal_audit';
    case EXTERNAL_AUDIT = 'external_audit';

    /**
     * Short code embedded in the non-conformity reference. Stable: business identifiers depend
     * on it, so it must not change once data exists.
     *
     * @return string the reference code (e.g. "AE")
     */
    public function code(): string
    {
        return match ($this) {
            self::INTERNAL => 'I',
            self::INTERNAL_AUDIT => 'AI',
            self::EXTERNAL_AUDIT => 'AE',
        };
    }

    /**
     * Human-facing label (Spanish, the application's UI language).
     *
     * @return string the display name
     */
    public function label(): string
    {
        return match ($this) {
            self::INTERNAL => 'Interna',
            self::INTERNAL_AUDIT => 'Auditoría interna',
            self::EXTERNAL_AUDIT => 'Auditoría externa',
        };
    }
}
