<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\LegalRequirement;
use App\Enum\Area;
use App\Form\LegalRequirementType;
use App\Repository\AuditLogRepository;
use App\Repository\LegalRequirementRepository;
use App\Security\Voter\AreaVoter;
use App\Service\AuditLogger;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * List of legal requirements and the registration/edit form (PC-06.03). Tracks the compliance
 * evaluation of each requirement; non-compliant ones can be escalated to a non-conformity.
 *
 * Requires authentication and per-area permission (Area::LEGAL_REQUIREMENT): READ to view,
 * WRITE to register or edit.
 */
#[Route('/legal-requirements')]
class LegalRequirementController extends AbstractController
{
    public function __construct(private readonly AuditLogger $auditLogger)
    {
    }

    /**
     * Lists every legal requirement.
     */
    #[Route('', name: 'legal_requirement_index', methods: ['GET'])]
    public function index(LegalRequirementRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::LEGAL_REQUIREMENT);

        return $this->render('legal_requirement/index.html.twig', [
            'requirements' => $repository->findAllOrdered(),
            'today' => new \DateTimeImmutable('today'),
        ]);
    }

    /**
     * Shows a legal requirement in detail: its evaluation of compliance and review schedule. The
     * {@see $today} reference date lets the template flag an overdue or approaching review.
     */
    #[Route('/{id}', name: 'legal_requirement_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(LegalRequirement $requirement, AuditLogRepository $auditLogs): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::LEGAL_REQUIREMENT);

        return $this->render('legal_requirement/show.html.twig', [
            'requirement' => $requirement,
            'today' => new \DateTimeImmutable('today'),
            'activity' => $auditLogs->findForSubject('LegalRequirement', (string) $requirement->getId()),
        ]);
    }

    /**
     * Registers a new requirement, assigning its autogenerated reference on save.
     */
    #[Route('/new', name: 'legal_requirement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em, LegalRequirementRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::LEGAL_REQUIREMENT);

        return $this->handleForm(new LegalRequirement(), $request, $em, $repository);
    }

    /**
     * Edits an existing requirement.
     */
    #[Route('/{id}/edit', name: 'legal_requirement_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(LegalRequirement $requirement, Request $request, EntityManagerInterface $em, LegalRequirementRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::LEGAL_REQUIREMENT);

        return $this->handleForm($requirement, $request, $em, $repository);
    }

    /**
     * Builds and processes the requirement form, persisting on a valid submission. On creation the
     * reference (RL-NN) is autogenerated.
     */
    private function handleForm(LegalRequirement $requirement, Request $request, EntityManagerInterface $em, LegalRequirementRepository $repository): Response
    {
        $isNew = null === $requirement->getId();

        $form = $this->createForm(LegalRequirementType::class, $requirement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($isNew) {
                $sequence = $repository->nextSequence();
                $requirement->setSequence($sequence)->setReference(sprintf('RL-%02d', $sequence));
            }

            $em->persist($requirement);
            $em->flush();

            $this->auditLogger->log(
                $isNew ? 'legalrequirement.created' : 'legalrequirement.updated',
                'LegalRequirement',
                (string) $requirement->getId(),
                $requirement->getReference(),
            );
            $this->addFlash('success', sprintf('Requisito legal %s guardado.', $requirement->getReference()));

            return $this->redirectToRoute('legal_requirement_show', ['id' => $requirement->getId()]);
        }

        return $this->render('legal_requirement/form.html.twig', [
            'form' => $form,
            'requirement' => $requirement,
            'isNew' => $isNew,
        ]);
    }
}
