<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\NonConformity;
use App\Enum\Area;
use App\Enum\NonConformityStatus;
use App\Form\NonConformityType;
use App\Repository\NonConformityRepository;
use App\Security\Voter\AreaVoter;
use App\Service\AuditLogger;
use App\Service\NonConformityReferenceGenerator;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Non-conformity control list (F.11.0) and the registration/edit report (F.10.0).
 *
 * Requires authentication and per-area permission (Area::NONCONFORMITY): READ to view,
 * WRITE to register or edit.
 */
#[Route('/non-conformities')]
class NonConformityController extends AbstractController
{
    public function __construct(
        private readonly AuditLogger $auditLogger,
        private readonly NonConformityReferenceGenerator $referenceGenerator,
    ) {
    }

    /**
     * Lists every non-conformity (the F.11.0 control list).
     */
    #[Route('', name: 'non_conformity_index', methods: ['GET'])]
    public function index(NonConformityRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::NONCONFORMITY);

        return $this->render('non_conformity/index.html.twig', [
            'nonConformities' => $repository->findAllOrdered(),
        ]);
    }

    /**
     * Shows a non-conformity in detail, including its corrective actions (the PAC).
     */
    #[Route('/{id}', name: 'non_conformity_show', requirements: ['id' => '\d+'], methods: ['GET'])]
    public function show(NonConformity $nonConformity): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::NONCONFORMITY);

        return $this->render('non_conformity/show.html.twig', [
            'nonConformity' => $nonConformity,
        ]);
    }

    /**
     * Registers a new non-conformity, assigning its autogenerated reference on save.
     */
    #[Route('/new', name: 'non_conformity_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::NONCONFORMITY);

        return $this->handleForm(new NonConformity(), $request, $em);
    }

    /**
     * Edits an existing non-conformity. The {@see NonConformity} is resolved from the {id} route
     * parameter by Symfony's entity value resolver.
     */
    #[Route('/{id}/edit', name: 'non_conformity_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(NonConformity $nonConformity, Request $request, EntityManagerInterface $em): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::NONCONFORMITY);

        return $this->handleForm($nonConformity, $request, $em);
    }

    /**
     * Builds and processes the non-conformity form, persisting on a valid submission. On creation
     * the reference is autogenerated; the closing date is kept in sync with the status.
     */
    private function handleForm(NonConformity $nonConformity, Request $request, EntityManagerInterface $em): Response
    {
        $isNew = null === $nonConformity->getId();

        $form = $this->createForm(NonConformityType::class, $nonConformity);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($isNew) {
                $this->referenceGenerator->assign($nonConformity);
            }
            $this->syncClosedAt($nonConformity);

            $em->persist($nonConformity);
            $em->flush();

            $this->auditLogger->log(
                $isNew ? 'nonconformity.created' : 'nonconformity.updated',
                'NonConformity',
                (string) $nonConformity->getId(),
                $nonConformity->getReference(),
            );
            $this->addFlash('success', sprintf('No conformidad %s guardada.', $nonConformity->getReference()));

            return $this->redirectToRoute('non_conformity_index');
        }

        return $this->render('non_conformity/form.html.twig', [
            'form' => $form,
            'nonConformity' => $nonConformity,
            'isNew' => $isNew,
        ]);
    }

    /**
     * Keeps the closing date consistent with the status: stamped when closed (if not already),
     * cleared otherwise (e.g. when reopened).
     */
    private function syncClosedAt(NonConformity $nonConformity): void
    {
        if (NonConformityStatus::CLOSED === $nonConformity->getStatus()) {
            if (null === $nonConformity->getClosedAt()) {
                $nonConformity->setClosedAt(new \DateTimeImmutable());
            }

            return;
        }

        $nonConformity->setClosedAt(null);
    }
}
