<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Objective;
use App\Enum\Area;
use App\Form\ObjectiveType;
use App\Repository\ObjectiveRepository;
use App\Security\Voter\AreaVoter;
use App\Service\AuditLogger;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * List of environmental objectives and the registration/edit form (PG-06.04 / F.07.01). Tracks
 * the achievement status; unmet objectives can be escalated to a non-conformity.
 *
 * Requires authentication and per-area permission (Area::OBJECTIVE): READ to view, WRITE to manage.
 */
#[Route('/objectives')]
class ObjectiveController extends AbstractController
{
    public function __construct(private readonly AuditLogger $auditLogger)
    {
    }

    /**
     * Lists every objective.
     */
    #[Route('', name: 'objective_index', methods: ['GET'])]
    public function index(ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::OBJECTIVE);

        return $this->render('objective/index.html.twig', [
            'objectives' => $repository->findAllOrdered(),
        ]);
    }

    /**
     * Registers a new objective, assigning its autogenerated reference on save.
     */
    #[Route('/new', name: 'objective_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::OBJECTIVE);

        return $this->handleForm(new Objective(), $request, $em, $repository);
    }

    /**
     * Edits an existing objective.
     */
    #[Route('/{id}/edit', name: 'objective_edit', requirements: ['id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(Objective $objective, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::OBJECTIVE);

        return $this->handleForm($objective, $request, $em, $repository);
    }

    /**
     * Builds and processes the objective form, persisting on a valid submission. On creation the
     * reference (OBJ-NN) is autogenerated.
     */
    private function handleForm(Objective $objective, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $isNew = null === $objective->getId();

        $form = $this->createForm(ObjectiveType::class, $objective);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($isNew) {
                $sequence = $repository->nextSequence();
                $objective->setSequence($sequence)->setReference(sprintf('OBJ-%02d', $sequence));
            }

            $em->persist($objective);
            $em->flush();

            $this->auditLogger->log(
                $isNew ? 'objective.created' : 'objective.updated',
                'Objective',
                (string) $objective->getId(),
                $objective->getReference(),
            );
            $this->addFlash('success', sprintf('Objetivo %s guardado.', $objective->getReference()));

            return $this->redirectToRoute('objective_index');
        }

        return $this->render('objective/form.html.twig', [
            'form' => $form,
            'objective' => $objective,
            'isNew' => $isNew,
        ]);
    }
}
