<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\Objective;
use App\Enum\Area;
use App\Form\ObjectiveType;
use App\Repository\AuditLogRepository;
use App\Repository\ObjectiveRepository;
use App\Security\Voter\AreaVoter;
use App\Service\AuditLogger;
use App\Util\CopyForward;
use App\Util\SchoolYear;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

/**
 * Annual register of environmental objectives (PG-06.04 / F.07.01): list a course's objectives and
 * add/edit one, plus copy the previous course forward as drafts. Objectives are redacted anew each
 * course, so the register is grouped by school year (like the sibling registers F.04.0 and F.06.0).
 * An unmet objective is a candidate for opening a non-conformity.
 *
 * Requires authentication and per-area permission (Area::OBJECTIVE): READ to view, WRITE to manage.
 */
#[Route('/objectives')]
class ObjectiveController extends AbstractController
{
    public function __construct(private readonly AuditLogger $auditLogger)
    {
    }

    /**
     * Redirects to the current course's objectives register.
     */
    #[Route('', name: 'objective_index', methods: ['GET'])]
    public function index(): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::OBJECTIVE);

        return $this->redirectToRoute('objective_year', ['schoolYear' => SchoolYear::current(new \DateTimeImmutable())]);
    }

    /**
     * Lists the objectives recorded for the given school year.
     */
    #[Route('/{schoolYear}', name: 'objective_year', requirements: ['schoolYear' => '\d{4}-\d{4}'], methods: ['GET'])]
    public function year(string $schoolYear, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::OBJECTIVE);

        return $this->render('objective/index.html.twig', [
            'schoolYear' => $schoolYear,
            'previousSchoolYear' => SchoolYear::previous($schoolYear),
            'nextSchoolYear' => SchoolYear::next($schoolYear),
            'objectives' => $repository->findForSchoolYear($schoolYear),
            'previousYearCount' => $repository->countForSchoolYear(SchoolYear::previous($schoolYear)),
        ]);
    }

    /**
     * Shows an objective in detail (the F.07.01 record of the course). The {@see Objective} is
     * resolved from the {id} route parameter and checked to belong to the course in the route, so a
     * mismatched URL 404s instead of showing a record filed under the wrong year.
     */
    #[Route('/{schoolYear}/{id}', name: 'objective_show', requirements: ['schoolYear' => '\d{4}-\d{4}', 'id' => '\d+'], methods: ['GET'])]
    public function show(string $schoolYear, Objective $objective, AuditLogRepository $auditLogs): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::READ, Area::OBJECTIVE);

        if ($objective->getSchoolYear() !== $schoolYear) {
            throw $this->createNotFoundException('The objective does not belong to the given course.');
        }

        return $this->render('objective/show.html.twig', [
            'objective' => $objective,
            'schoolYear' => $schoolYear,
            'activity' => $auditLogs->findForSubject('Objective', (string) $objective->getId()),
        ]);
    }

    /**
     * Registers a new objective for the given course, assigning its autogenerated reference on save.
     */
    #[Route('/{schoolYear}/new', name: 'objective_new', requirements: ['schoolYear' => '\d{4}-\d{4}'], methods: ['GET', 'POST'])]
    public function new(string $schoolYear, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::OBJECTIVE);

        $objective = (new Objective())->setSchoolYear($schoolYear);

        return $this->handleForm($objective, $schoolYear, $request, $em, $repository);
    }

    /**
     * Edits an existing objective. The {@see Objective} is resolved from the {id} route parameter and
     * checked to belong to the course in the route.
     */
    #[Route('/{schoolYear}/{id}/edit', name: 'objective_edit', requirements: ['schoolYear' => '\d{4}-\d{4}', 'id' => '\d+'], methods: ['GET', 'POST'])]
    public function edit(string $schoolYear, Objective $objective, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::OBJECTIVE);

        if ($objective->getSchoolYear() !== $schoolYear) {
            throw $this->createNotFoundException('The objective does not belong to the given course.');
        }

        return $this->handleForm($objective, $schoolYear, $request, $em, $repository);
    }

    /**
     * Copies the objectives of the previous course into this one, as editable drafts. Only objectives
     * whose description is not already present in the current course are brought over (matched
     * case-insensitively, trimmed), so it is safe to run with the course empty or half-filled and it
     * never creates duplicates. Each copy gets a fresh reference (OBJ-NN). CSRF-protected POST.
     */
    #[Route('/{schoolYear}/copy-previous', name: 'objective_copy_previous', requirements: ['schoolYear' => '\d{4}-\d{4}'], methods: ['POST'])]
    public function copyFromPreviousYear(string $schoolYear, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $this->denyAccessUnlessGranted(AreaVoter::WRITE, Area::OBJECTIVE);

        if (!$this->isCsrfTokenValid('copy_previous_objective'.$schoolYear, (string) $request->request->get('_token'))) {
            throw $this->createAccessDeniedException('Token CSRF inválido.');
        }

        $previousSchoolYear = SchoolYear::previous($schoolYear);
        $toCopy = CopyForward::missing(
            $repository->findForSchoolYear($previousSchoolYear),
            $repository->findForSchoolYear($schoolYear),
            static fn (Objective $o): string => self::normaliseDescription($o->getDescription()),
        );

        // Reserve the sequence once and increment in memory: nextSequence() reads the DB and would
        // hand the same number to every copy before the flush, breaking the unique reference.
        $sequence = $repository->nextSequence();
        foreach ($toCopy as $objective) {
            $copy = $objective->copyForSchoolYear($schoolYear)
                ->setSequence($sequence)
                ->setReference(sprintf('OBJ-%02d', $sequence));
            $em->persist($copy);
            ++$sequence;
        }
        $em->flush();

        $copied = \count($toCopy);
        if ($copied > 0) {
            $this->auditLogger->log(
                'objective.copied_from_previous',
                'Objective',
                $schoolYear,
                sprintf('%d objetivos copiados de %s a %s', $copied, $previousSchoolYear, $schoolYear),
            );
            $this->addFlash('success', sprintf('Se han copiado %d objetivos de %s.', $copied, $previousSchoolYear));
        } else {
            $this->addFlash('success', sprintf('No había nada nuevo que copiar de %s.', $previousSchoolYear));
        }

        return $this->redirectToRoute('objective_year', ['schoolYear' => $schoolYear]);
    }

    /**
     * Normalises an objective's description for duplicate detection: trimmed and lower-cased so the
     * same objective is not copied twice across courses.
     *
     * @param string $description the raw objective description
     *
     * @return string the normalised key
     */
    private static function normaliseDescription(string $description): string
    {
        return mb_strtolower(trim($description));
    }

    /**
     * Builds and processes the objective form, persisting on a valid submission. On creation the
     * reference (OBJ-NN) is autogenerated.
     */
    private function handleForm(Objective $objective, string $schoolYear, Request $request, EntityManagerInterface $em, ObjectiveRepository $repository): Response
    {
        $isNew = null === $objective->getId();

        $form = $this->createForm(ObjectiveType::class, $objective);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($isNew) {
                $sequence = $repository->nextSequence();
                $objective->setSequence($sequence)->setReference(sprintf('OBJ-%02d', $sequence));
            }

            $em->persist($objective);
            $em->flush();

            $this->auditLogger->log(
                $isNew ? 'objective.created' : 'objective.updated',
                'Objective',
                (string) $objective->getId(),
                $objective->getReference(),
            );
            $this->addFlash('success', sprintf('Objetivo %s guardado.', $objective->getReference()));

            return $this->redirectToRoute('objective_year', ['schoolYear' => $schoolYear]);
        }

        return $this->render('objective/form.html.twig', [
            'form' => $form,
            'objective' => $objective,
            'schoolYear' => $schoolYear,
            'isNew' => $isNew,
        ]);
    }
}
