<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\LegalRequirement;
use App\Enum\ComplianceStatus;
use App\Enum\EvaluationFrequency;
use App\Enum\LegalScope;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form to register or edit a {@see LegalRequirement} (report "Lista de requisitos legales"). The
 * reference is autogenerated by the controller on creation, so it is not part of the form.
 *
 * @extends AbstractType<LegalRequirement>
 */
class LegalRequirementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('legalProvision', TextType::class, [
                'label' => 'Disposición legal',
                'help' => 'La norma o legislación (p. ej. "Ley 7/2022 de residuos").',
            ])
            ->add('scope', EnumType::class, [
                'class' => LegalScope::class,
                'label' => 'Ámbito',
                'choice_label' => static fn (LegalScope $s): string => $s->label(),
            ])
            ->add('environmentalVector', TextType::class, [
                'label' => 'Vector ambiental afectado',
                'required' => false,
                'help' => 'P. ej. residuos, vertidos, emisiones, ruido.',
            ])
            ->add('specificRequirement', TextareaType::class, [
                'label' => 'Requisito específico',
                'help' => 'Tarea o control concreto que debe cumplir el centro.',
            ])
            ->add('complianceEvidence', TextareaType::class, [
                'label' => 'Evidencia de cumplimiento',
                'required' => false,
            ])
            ->add('complianceStatus', EnumType::class, [
                'class' => ComplianceStatus::class,
                'label' => 'Evaluación del cumplimiento',
                'choice_label' => static fn (ComplianceStatus $c): string => $c->label(),
            ])
            ->add('evaluationFrequency', EnumType::class, [
                'class' => EvaluationFrequency::class,
                'label' => 'Frecuencia de evaluación',
                'required' => false,
                'placeholder' => 'Sin especificar',
                'choice_label' => static fn (EvaluationFrequency $f): string => $f->label(),
            ])
            ->add('lastReviewedOn', DateType::class, [
                'label' => 'Fecha de la última revisión',
                'widget' => 'single_text',
                'required' => false,
                'input' => 'datetime_immutable',
                'help' => 'La próxima revisión se calcula sola: última revisión + frecuencia de evaluación.',
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => LegalRequirement::class,
        ]);
    }
}
