<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\NonConformity;
use App\Entity\SystemAudit;
use App\Entity\User;
use App\Enum\NonConformityOrigin;
use App\Enum\ProcessType;
use App\Repository\SystemAuditRepository;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form to register or edit a {@see NonConformity} (report F.10.0). The reference is autogenerated
 * by the controller on creation, so it is not part of the form.
 *
 * @extends AbstractType<NonConformity>
 */
class NonConformityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('openedAt', DateType::class, [
                'label' => 'Fecha de apertura',
                'widget' => 'single_text',
                // The entity stores an immutable date; without this the form would hand back a
                // mutable \DateTime and the typed setter would fail.
                'input' => 'datetime_immutable',
            ])
            ->add('origin', EnumType::class, [
                'class' => NonConformityOrigin::class,
                'label' => 'Origen',
                'choice_label' => static fn (NonConformityOrigin $o): string => $o->label(),
                'help_slug' => 'nc-origen',
            ])
            ->add('originDetail', TextType::class, [
                'label' => 'Detalle del origen',
                'required' => false,
                'help' => 'P. ej. la fase de la auditoría ("Fase I") o la iniciativa interna.',
            ])
            ->add('audit', EntityType::class, [
                'class' => SystemAudit::class,
                'label' => 'Auditoría de origen',
                'required' => false,
                'placeholder' => 'Ninguna',
                'help' => 'Si proviene de una auditoría, vincúlala para que quede trazada en su informe.',
                'choice_label' => static fn (SystemAudit $a): string => sprintf(
                    'Auditoría %s %d%s',
                    $a->getType()->label(),
                    $a->getYear(),
                    null !== $a->getConductedOn() ? ' ('.$a->getConductedOn()->format('d/m/Y').')' : '',
                ),
                'query_builder' => static fn (SystemAuditRepository $r) => $r->createQueryBuilder('a')
                    ->orderBy('a.year', 'DESC')
                    ->addOrderBy('a.conductedOn', 'DESC'),
            ])
            ->add('affectedProcess', EnumType::class, [
                'class' => ProcessType::class,
                'label' => 'Proceso afectado',
                'required' => false,
                'placeholder' => 'Sin especificar',
                'choice_label' => static fn (ProcessType $p): string => $p->label(),
            ])
            ->add('isoClause', TextType::class, [
                'label' => 'Apartado de la norma ISO 14001',
                'required' => false,
                'help' => 'Requisito incumplido, p. ej. "6.1.2".',
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Descripción',
                'help' => 'Incumplimiento detectado y evidencias en las que se fundamenta.',
            ])
            ->add('rootCause', TextareaType::class, [
                'label' => 'Análisis de causas',
                'required' => false,
                'help' => 'Motivo que la origina (puede completarse durante la evaluación).',
                'help_slug' => 'nc-causa-raiz',
            ])
            ->add('responsible', EntityType::class, [
                'class' => User::class,
                'label' => 'Responsable de la no conformidad',
                'required' => false,
                'placeholder' => 'Sin asignar',
                'choice_label' => static fn (User $u): string => $u->getFullName(),
                'query_builder' => static fn (UserRepository $r) => $r->createQueryBuilder('u')
                    ->where('u.active = true')
                    ->orderBy('u.fullName', 'ASC'),
            ]);
        // El ESTADO no es un campo editable: se gobierna por las transiciones con CTAs
        // (non_conformity_change_status), donde vive la regla de cierre (canBeClosed). Editarlo aquí
        // sería una puerta trasera que se saltaría esa regla.
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => NonConformity::class,
        ]);
    }
}
