<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\EnvironmentalAspect;
use App\Entity\Objective;
use App\Entity\User;
use App\Enum\ObjectiveStatus;
use App\Repository\EnvironmentalAspectRepository;
use App\Repository\UserRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\EnumType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Form to register or edit an {@see Objective} (register F.07.01). The reference is autogenerated
 * by the controller on creation, so it is not part of the form.
 *
 * @extends AbstractType<Objective>
 */
class ObjectiveType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('description', TextareaType::class, [
                'label' => 'Descripción del objetivo',
                'help' => 'Incluye la meta (p. ej. "Reducir el consumo de agua en un 5%").',
            ])
            ->add('responsible', EntityType::class, [
                'class' => User::class,
                'label' => 'Responsable',
                'required' => false,
                'placeholder' => 'Sin asignar',
                'choice_label' => static fn (User $u): string => $u->getFullName(),
                'query_builder' => static fn (UserRepository $r) => $r->createQueryBuilder('u')
                    ->where('u.active = true')
                    ->orderBy('u.fullName', 'ASC'),
            ])
            ->add('relatedAspect', EntityType::class, [
                'class' => EnvironmentalAspect::class,
                'label' => 'Aspecto significativo relacionado',
                'required' => false,
                'placeholder' => 'Ninguno',
                'choice_label' => static fn (EnvironmentalAspect $a): string => $a->getName(),
                'query_builder' => static fn (EnvironmentalAspectRepository $r) => $r->createQueryBuilder('a')
                    ->where('a.active = true')
                    ->orderBy('a.name', 'ASC'),
                'help' => 'Aspecto ambiental que motiva el objetivo, si aplica.',
                'help_slug' => 'objetivo-aspecto',
            ])
            ->add('targetPeriod', TextType::class, [
                'label' => 'Periodo',
                'required' => false,
                'help' => 'P. ej. "enero 2025 a marzo 2026".',
            ])
            ->add('status', EnumType::class, [
                'class' => ObjectiveStatus::class,
                'label' => 'Cumplimiento',
                'choice_label' => static fn (ObjectiveStatus $s): string => $s->label(),
                'help_slug' => 'objetivo-cumplimiento',
            ])
            ->add('lastReviewedOn', DateType::class, [
                'label' => 'Fecha de la última revisión',
                'widget' => 'single_text',
                'required' => false,
                'input' => 'datetime_immutable',
            ])
            ->add('notes', TextareaType::class, [
                'label' => 'Observaciones',
                'required' => false,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Objective::class,
        ]);
    }
}
